### ISSUE TITLE
Unsupported SQL statements lock the UI with the spin wheel

### ISSUE THREAD

**Issue by andrewxhill** [tablelandnetwork/console#59]
<img width="948" alt="Screen Shot 2022-12-20 at 10 02 29 AM" src="https://user-images.githubusercontent.com/370259/208735140-00ab6923-6561-4cd2-9cb7-2edc0e944949.png">

There is no way to abort or get out of that query above. 

> SELECT * FROM generate_series(1,20);

I tested it on a few variations of unsupported sql and it always went the same.

**Comment by awmuncy** [comment]
Invalid SQL should now be un-submittable. I'm closing this for now, but feel free to re-open in.
