### ISSUE TITLE
After successful insert/update it doesn't update the preview data

### ISSUE THREAD

**Issue by andrewxhill** [tablelandnetwork/console#60]
<img width="907" alt="Screen Shot 2022-12-20 at 10 07 03 AM" src="https://user-images.githubusercontent.com/370259/208735880-6691de30-399b-42ba-b934-5c9c00e664f4.png">

See above, the insert is successful, but i need to go and rewrite my query statement to see it in the table below (currently indicating an empty table).

**Comment by awmuncy** [comment]
Console now query tables after inserts.

**Comment by andrewxhill** [comment]
huzzah
